---
title: "model_phenotypes.Rmd"
author: "Andrea Estandia"
date: "20/03/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
source("./src/0.0_island_rule_source.R")
```

Read data
```{r}
pheno <- 
  read_csv(file.path(data_path, "phenotypes/phenotypes+SMC2+AE.csv")) %>% 
  mutate(wing_weight=Wing/Weight) %>% 
  mutate(wing_weight=ifelse(wing_weight=="Inf", NA, wing_weight)) %>% 
  mutate(tarsus_weight=Tarsus/Weight) %>% 
  mutate(tarsus_weight=ifelse(tarsus_weight=="Inf", NA, tarsus_weight))

pheno[pheno=="<NA>"]=NA
```

PCA prep with a) head, wing, tarsus, tail b) bill measurements
```{r}
body_pca <-
  princomp(~Wing+
             Tarsus+
             Tail+
             HeadLength,
           data=pheno,
           scores=TRUE,
           cor=TRUE,
           na.action=na.exclude)

colnames(body_pca$scores) <- 
  c("body_PC1", "body_PC2", "body_PC3", "body_PC4")

bill_pca <-
  princomp(~Bill_length_posterior+
             Bill_depth_anterior+
             Bill_width_anterior,
           data=pheno,
           scores=TRUE,
           cor=TRUE,
           na.action=na.exclude)

colnames(bill_pca$scores) <- 
  c("bill_PC1", "bill_PC2", "bill_PC3")

pheno <- 
  cbind(pheno,body_pca$scores) %>% 
  cbind(bill_pca$scores)
```

Test whether island-colonising silvereyes are larger (body PC1)
```{r}
#Set prior
prior <- 
  set_prior(class="b", 
            "normal(0,10)")

#Run null model 
model_body_null <- 
  brm(body_PC1 ~ (1|pop),
            chains = 4,
            iter = 4000,
            warmup = 1000,
            data = pheno)

#Run model
model <- 
  brm(body_PC1 ~ colonisation_label_brms + 
                     (1|pop),
            prior = prior,
            chains = 4,
            save_pars = save_pars(all = TRUE),
            iter = 4000,
            warmup = 1000,
            data = pheno)

#Save model
saveRDS(model, 
        file.path(reports_path, 
                         "brms", 
                         "brms_model.RDS"))

#Compare null model and model with loo
model$loo <- loo(model)
model_body_null$loo <- loo(model_body_null)
loo_compare(model$loo,model_body_null$loo)

#Plot posteriors by col time and pop
post_col <-
pheno %>%
  group_by(pop) %>% 
  data_grid(colonisation_label_brms) %>%
  add_epred_draws(model) %>%
  ggplot(aes(x = .epred, y = colonisation_label_brms, 
             fill=colonisation_label_brms)) +
  stat_dist_halfeye()+
  theme_minimal() +
  scale_y_discrete(limits = c("source",
                              "z<200",
                              "z~4000", 
                              "z~100000", 
                              "z~150000"),
                   labels = c("Source",
                              "<200",
                              "~4000", 
                              "~100000", 
                              "~150000"))+
  scale_fill_manual(values=c(
                             "#234551",
                             "#ab5c94",
                             "#e8c268",
                             "#289C8F",
                             "#e66e4f"))+
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.text.y = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    title = "Posterior predictive draws of the group means",
    subtitle = "Body size (PC1)",
    x = "\nBody size (PC1)"
  )

#Plot posteriors by col time and pop
post_pop <-
pheno %>%
  group_by(pop) %>% 
  data_grid(colonisation_label_brms) %>%
  add_epred_draws(model) %>%
  ggplot(aes(x = .epred, y = pop, 
             fill=colonisation_label_brms)) +
  stat_dist_halfeye()+
  theme_minimal() +
  scale_y_discrete(limits = c("Mainland",
                              "Tasmania",
                              "New_Zealand", 
                              "Chatham", 
                              "Norfolk_Island", 
                              "French_Polynesia", 
                              "Heron_Island",
                              "Lord_Howe_Island",
                              "Grand_Terre",
                              "Mare",
                              "Lifou",
                              "Ouvea",
                              "Tanna",
                              "Efate",
                              "Santo",
                              "Malekula",
                              "Pentecost",
                              "Ambrym",
                              "Ambae",
                              "Gaua",
                              "Vanua_Lava"),
                   labels= c("Australian mainland",
                              "Tasmania", 
                              "New Zealand", 
                              "Chatham Island", 
                              "Norfolk Island", 
                              "French Polynesia",
                              "Heron Island",
                              "Lord Howe Island",
                              "Grand Terre",
                              "Mare",
                              "Lifou",
                              "Ouvea",
                              "Tanna",
                              "Efate",
                              "Espiritu Santo",
                              "Malekula",
                              "Pentecost",
                              "Ambrym",
                              "Ambae",
                              "Gaua",
                              "Vanua Lava"))+
  scale_fill_manual(labels=c("Source",
                            "<200",
                            "~100000",
                            "~150000",
                            "~4000"),
                      name="Colonisation time",
                      values=c(
                             "#234551",
                             "#ab5c94",
                             "#e8c268",
                             "#289C8F",
                             "#e66e4f"))+
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.text.y = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    title = "",
    x = "\nBody size (PC1)"
  )

```

Repeat same process for bill size (Bill PC1)
```{r}
prior <- 
  set_prior(class="b", 
            "normal(0,10)")

model_bill_null <- 
  brm(bill_PC1 ~ (1|pop),
            chains = 4,
            iter = 4000,
            warmup = 1000,
            data = pheno)

model_bill <- 
  brm(bill_PC1 ~ colonisation_label_brms + 
                     (1|pop),
            prior = prior,
            save_pars = save_pars(all = TRUE),
            chains = 4,
            iter = 4000,
            warmup = 1000,
            data = pheno)

saveRDS(model_bill, "brms_model_bill.RDS")

model_bill$loo <- loo(model_bill, moment_match = TRUE)
model_bill_null$loo <- loo(model_bill_null)
loo_compare(model_bill$loo,model_bill_null$loo)

post_col_bill <-
pheno %>%
  group_by(pop) %>% 
  data_grid(colonisation_label_brms) %>%
  add_epred_draws(model_bill) %>%
  ggplot(aes(x = .epred, y = colonisation_label_brms, 
             fill=colonisation_label_brms)) +
  stat_dist_halfeye()+
  theme_minimal() +
  scale_y_discrete(limits = c("source",
                              "z<200",
                              "z~4000", 
                              "z~100000", 
                              "z~150000"),
                   labels = c("Source",
                              "<200",
                              "~4000", 
                              "~100000", 
                              "~150000"))+
  scale_fill_manual(values=c(
                             "#234551",
                             "#ab5c94",
                             "#e8c268",
                             "#289C8F",
                             "#e66e4f"))+
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.text.y = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    title = "Posterior estimates of the group means",
    subtitle = "Bill size (PC1)",
    x = "\nBill size (PC1)"
  )

post_pop_bill <-
pheno %>%
  group_by(pop) %>% 
  data_grid(colonisation_label_brms) %>%
  add_epred_draws(model_bill) %>%
  ggplot(aes(x = .epred, y = pop, 
             fill=colonisation_label_brms)) +
  stat_dist_halfeye()+
  theme_minimal() +
  scale_y_discrete(limits = c("Mainland",
                              "Tasmania",
                              "French_Polynesia", 
                              "New_Zealand", 
                              "Chatham", 
                              "Norfolk_Island", 
                              "Heron_Island",
                              "Lord_Howe_Island",
                              "Grand_Terre",
                              "Mare",
                              "Lifou",
                              "Ouvea",
                              "Tanna",
                              "Efate",
                              "Malekula",
                              "Pentecost",
                              "Ambae",
                              "Ambrym",
                              "Santo",
                              "Gaua",
                              "Vanua_Lava"),
                   labels= c("Australian mainland",
                              "Tasmania",
                              "French Polynesia", 
                              "New Zealand", 
                              "Chatham Island", 
                              "Norfolk Island", 
                              "Heron Island",
                              "Lord Howe Island",
                              "Grand Terre",
                              "Mare",
                              "Lifou",
                              "Ouvea",
                              "Tanna",
                              "Efate",
                              "Malekula",
                              "Pentecost",
                              "Ambae",
                              "Ambrym",
                              "Espiritu Santo",
                              "Gaua",
                              "Vanua Lava"))+
  scale_fill_manual(labels=c("Source",
                            "<200",
                            "~100000",
                            "~150000",
                            "~4000"),
                      name="Colonisation time",
                      values=c(
                             "#234551",
                             "#ab5c94",
                             "#e8c268",
                             "#289C8F",
                             "#e66e4f"))+
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.text.y = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    title = "",
    x = "\nBill size (PC1)"
  )

plot_pheno <- 
  (post_col+post_pop+post_col_bill+post_pop_bill)+plot_layout(nrow=2,ncol=2)+
  plot_annotation(tag_levels = "A")

```

Save plot - Figure S1
```{r}
ggsave(plot_pheno,
       filename = file.path(reports_path, 
                            "plots", 
                            "plot_pheno_figS1.pdf"),
       device="pdf",width = 11.5, height = 10)
```

